### PR TITLE
liblights: fix redefinition errors

### PR DESCRIPTION
**Pull request by Joshndroid**

### CODE REVIEW

**Comment by Joshndroid** [comment]
we get errors due to the prior definition in hardware/samsung/liblights

it looks for whether liblights is set to true within hardware/samsung/liblights/android.mk first... this will fix that

**Comment by ShevT** [comment]
Yes I know. In the local repo I have long been corrected

**Comment by ShevT** [comment]
I have a lot of changes. I have not put everything

**Comment by Joshndroid** [comment]
i totally understand lol

**Pull request closed without merging**
